### ISSUE TITLE
Changing REM base

### ISSUE THREAD

**Issue by whatsnewsaes** [CodesummitGoats/Sparkplug-Framework#55]
Looking for some feedback on this 

currently 1rem = 16px

This is fine, except it makes calculation px value hard. how many REM is 22px? If you can calculate that in your head, you're smart.

html {
   font-size:62.5%
}

If we set the html element to the following it would make 1 rem = 10px. super simple to convert that in your head. 15px = 1.5rem, 22px = 2.2rem, etc...

I do think this would be a good change. The only reason I can see for not doing this is that we've done it the other way for so long and would have to go back and change the rem values.

What do you think @gr33k01

**Comment by gr33k01** [comment]
I like this a lot. As long as the 1rem = 22px isn't an accepted standard. I'd like to see what other people are doing, not because it's necessarily the right thing, but just to see other thoughts out there.

Otherwise, I really like this.

**Comment by whatsnewsaes** [comment]
One big disadvantage is that media-queries do NOT inherit global font-size settings. sooo if we set font-size to 62.5% on the HTML element 2.2ems = 22px for fonts, but 2.2ems = 33px in media queries... -- Yes, very confusing.

**Comment by whatsnewsaes** [comment]
changed to em base 9bd1a4e0ee0e4154c4b8e18d0384546786877364
